#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
cd ..
BACKUP="$(mktemp -dup .)"
install -d -m 0750 -o "$USER" -g "$GROUP" "$BACKUP"
PRIMARY="$1"
PRIMARY_CONNINFO="host=$PRIMARY application_name=$(hostname) target_session_attrs=read-write"
if pg_basebackup \
    --dbname="$PRIMARY_CONNINFO" \
    --pgdata="$BACKUP" \
    --progress \
    --verbose \
    --wal-method=stream; then
    rm -rf "$PGDATA"
    mv "$BACKUP" "$PGDATA"
    cd "$PGDATA"
    touch standby.signal
    cat >>postgresql.auto.conf <<EOF
primary_conninfo = '$PRIMARY_CONNINFO'
EOF
else
    rm -rf "$BACKUP"
    cd "$PGDATA"
fi
