#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
PRIMARY="$(etcdctl get primary --endpoints="$ETCD" --print-value-only)"
test -n "$PRIMARY"
pg_isready --host="$PRIMARY"
HOSTNAME="$(hostname)"
pg_basebackup \
    --dbname="host=$PRIMARY application_name=$HOSTNAME" \
    --pgdata="$PGDATA" \
    --progress \
    --verbose \
    --wal-method=stream
SLOT="$(echo "$HOSTNAME" | tr '.' '_')"
psql --host="$PRIMARY" --command="SELECT CASE WHEN s IS NULL THEN pg_create_physical_replication_slot(slot_name) END FROM (VALUES ('$SLOT')) AS v (slot_name) LEFT JOIN pg_replication_slots AS s USING (slot_name)"
touch "$PGDATA/standby.signal"
cat >>"$PGDATA/postgresql.auto.conf" <<EOF
primary_conninfo = 'host=$PRIMARY application_name=$HOSTNAME'
primary_slot_name = '$SLOT'

EOF
