#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
PRIMARY="$1"
if [ -f standby.signal ]; then
    test -n "$PRIMARY"
    PRIMARY_CONNINFO="host=$PRIMARY application_name=$(hostname) target_session_attrs=read-write"
    sed -i "/^primary_conninfo/cprimary_conninfo = '$PRIMARY_CONNINFO'" postgresql.auto.conf
    sed -i "/^pg_save.primary/cpg_save.primary = '$PRIMARY'" postgresql.auto.conf
    sed -i "/^pg_save.wait_primary/cpg_save.wait_primary = '$PRIMARY'" postgresql.auto.conf
else
    STATE="$(sed -n "s|^pg_save\.state = ||p" postgresql.auto.conf | tr -d "'")"
    test -n "$STATE"
    if [ "$STATE" == "wait_standby" ]; then
        test -n "$PRIMARY"
    fi
    if [ -n "$PRIMARY" ]; then
        /etc/service/postgres/rewind "$PRIMARY" || /etc/service/postgres/basebackup "$PRIMARY"
    fi
fi
