#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
if [ ! -f standby.signal ]; then
    if pg_isready --dbname="$PRIMARY_CONNINFO" && psql --quiet --tuples-only --no-align --dbname="$PRIMARY_CONNINFO" --command="SELECT now()"; then
        /etc/service/postgres/rewind || /etc/service/postgres/basebackup
    fi
fi
