#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
cat >>"$PGDATA/postgresql.conf" <<EOF

cluster_name = '$CLUSTER_NAME'
listen_addresses = '*'
max_logical_replication_workers = 0
max_sync_workers_per_subscription = 0
max_wal_senders = 0
wal_level = minimal
EOF
if [ -n "$ETCD" ]; then echo "custom.etcd = '$ETCD'" >>"$PGDATA/postgresql.conf"; fi
if [ -n "$SERVER_CERT" ] && [ -n "$SERVER_KEY" ]; then echo "ssl = on" >>"$PGDATA/postgresql.conf"; fi
if [ -n "$SERVER_CERT" ]; then echo "ssl_cert_file = '$SERVER_CERT'" >>"$PGDATA/postgresql.conf"; fi
if [ -n "$SERVER_KEY" ]; then echo "ssl_key_file = '$SERVER_KEY'" >>"$PGDATA/postgresql.conf"; fi
if [ -n "$SSL_CA_FILE" ]; then echo "ssl_ca_file = '$SSL_CA_FILE'" >>"$PGDATA/postgresql.conf"; fi
if [ -n "$SSL_CRL_FILE" ]; then echo "ssl_crl_file = '$SSL_CRL_FILE'" >>"$PGDATA/postgresql.conf"; fi
cat >>"$PGDATA/postgresql.conf" <<EOF

archive_cleanup_command = 'pg_archivecleanup -d "$HOME/pg_arclog" "%r" 2>>"$HOME/pg_log/pg_archivecleanup.log"'
archive_command = 'test ! -f "$HOME/pg_arclog/%f" && cp "%p" "$HOME/pg_arclog/%f"'
archive_mode = on
max_wal_senders = 10
wal_level = replica
EOF
