#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
cat >>postgresql.auto.conf <<EOF

archive_command = 'test ! -f "$ARCLOG/%f" && gzip -9 <"%p" >"$ARCLOG/%f"'
archive_mode = 'on'
auto_explain.log_analyze = 'on'
auto_explain.log_buffers = 'on'
auto_explain.log_min_duration = '100'
auto_explain.log_nested_statements = 'on'
auto_explain.log_triggers = 'on'
auto_explain.log_verbose = 'on'
cluster_name = '$CLUSTER_NAME'
custom.etcd = '$ETCD'
datestyle = 'iso, dmy'
hot_standby_feedback = 'on'
listen_addresses = '*'
log_connections = 'on'
log_hostname = 'on'
log_line_prefix = '%m [%p] %r %u@%d/%a '
log_min_messages = 'debug1'
max_logical_replication_workers = '0'
max_sync_workers_per_subscription = '0'
max_wal_senders = '3'
restore_command = 'test -f "$ARCLOG/%f" && gunzip <"$ARCLOG/%f" >"%p"'
shared_preload_libraries = 'auto_explain,pg_async,pg_save'
wal_compression = 'on'
wal_level = 'replica'
wal_log_hints = 'on'
wal_receiver_create_temp_slot = 'on'
EOF
