#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
PRIMARY="$1"
if [ -n "$PRIMARY" ]; then
    /etc/service/postgres/basebackup "$PRIMARY"
elif [ "$(echo "$HOST_NAMES" | tr "," "\n" | head -n1)" != "$(hostname)" ]; then
    exit 1
else
    initdb .
    /etc/service/postgres/conf
    /etc/service/postgres/hba
fi
