#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
PRIMARY="$(psql --quiet --tuples-only --no-align --dbname="host=$HOST_NAMES application_name=$(hostname) target_session_attrs=read-write" --command="SELECT current_setting('pg_save.hostname', false)" || echo "")"
if [ -n "$PRIMARY" ]; then
    /etc/service/postgres/basebackup
elif [ "$(echo "$HOST_NAMES" | tr "," "\n" | head -n1)" != "$(hostname)" ]; then
    exit 1
else
    initdb .
    /etc/service/postgres/conf
    /etc/service/postgres/hba
fi
