#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
HOSTNAME="$(hostname)"
PRIMARY="$(etcdctl get primary --endpoints="$ETCD" --print-value-only)"
TIMESTAMPTZ="$(date "+%F %T%Z")"
if [ -z "$PRIMARY" ]; then
    test "OK" == "$(etcdctl put primary "$HOSTNAME" --endpoints="$ETCD")"
    test "OK" == "$(etcdctl put "$HOSTNAME" "$TIMESTAMPTZ" --endpoints="$ETCD")"
    initdb "$PGDATA"
    /etc/service/postgres/conf
    /etc/service/postgres/hba
else
    PRIMARY_TIMESTAMPTZ="$(etcdctl get "$PRIMARY" --endpoints="$ETCD" --print-value-only)"
    PRIMARY_SECOND="$(ddiff "$PRIMARY_TIMESTAMPTZ" "$TIMESTAMPTZ" -f "%S")"
    if [ "$PRIMARY_SECOND" -gt "30" ]; then
        test "OK" == "$(etcdctl put primary "$HOSTNAME" --endpoints="$ETCD")"
        test "OK" == "$(etcdctl put "$HOSTNAME" "$TIMESTAMPTZ" --endpoints="$ETCD")"
        initdb "$PGDATA"
        /etc/service/postgres/conf
        /etc/service/postgres/hba
    else
        /etc/service/postgres/basebackup
    fi
fi
