#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
PRIMARY="$(psql --quiet --tuples-only --no-align --dbname="$PRIMARY_CONNINFO" --command="SELECT current_setting('custom.hostname', false)")"
test -n "$PRIMARY"
pg_rewind \
    --progress \
    --restore-target-wal \
    --source-server="host=$PRIMARY" \
    --target-pgdata=.
touch standby.signal
cat >>postgresql.auto.conf <<EOF
primary_conninfo = 'host=$PRIMARY application_name=$(hostname) target_session_attrs=read-write'
EOF
