#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
PRIMARY="$(etcdctl get primary --endpoints="$ETCD" --print-value-only)"
test -n "$PRIMARY"
pg_isready --host="$PRIMARY"
HOSTNAME="$(hostname)"
pg_rewind \
    --debug \
    --progress \
    --restore-target-wal \
    --source-server="host=$PRIMARY application_name=$HOSTNAME" \
    --target-pgdata=.
touch standby.signal
cat >>postgresql.auto.conf <<EOF
primary_conninfo = 'host=$PRIMARY application_name=$HOSTNAME'

EOF
