#!/bin/sh -eux

realpath "$0"
cd "$(dirname "$0")"
chmod 755 supervise
chown "$USER":"$GROUP" supervise/ok supervise/control supervise/status
cd "$HOME"
install -d -m 1775 -o "$USER" -g "$GROUP" /run/postgresql /var/log/postgresql
rm -f postmaster.pid /run/postgresql/.s.PGSQL.* /tmp/.s.PGSQL.*
exec chpst -u "$USER":"$GROUP" pg_save
